CREATE ROLE "hive" WITH LOGIN PASSWORD 'hivepassword';
CREATE DATABASE "hive" WITH TEMPLATE='template0' ENCODING='UTF8' OWNER="hive";
REVOKE CONNECT ON DATABASE "hive" FROM "public";
GRANT ALL ON DATABASE "hive" TO "hive";
