trino:
  target: dev
  outputs:
    dev:
      type: trino
      method: ldap
      user: "{{ env_var('DBT_ENV_SECRET_DBT_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_DBT_PASSWORD') }}"
      host: nginx
      port: 9999
      database: iceberg
      schema: bronze
      threads: 1
      http_scheme: https
      session_properties:
        query_max_run_time: 2h


# trino:
#   target: dev
#   outputs:
#     dev:
#       type: trino
#       host: nginx
#       port: 9999
#       method: oauth_console
#       database: iceberg
#       schema: bronze
#       threads: 1
#       http_scheme: https
#       session_properties:
#         query_max_run_time: 2h
